# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_xkb_config', [dirname(__file__)])
        except ImportError:
            import _xkb_config
            return _xkb_config
        if fp is not None:
            try:
                _mod = imp.load_module('_xkb_config', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _xkb_config = swig_import_helper()
    del swig_import_helper
else:
    import _xkb_config
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


GROUP_POLICY_GLOBAL = _xkb_config.GROUP_POLICY_GLOBAL
GROUP_POLICY_PER_WINDOW = _xkb_config.GROUP_POLICY_PER_WINDOW
GROUP_POLICY_PER_APPLICATION = _xkb_config.GROUP_POLICY_PER_APPLICATION
class t_xkb_kbd_config(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, t_xkb_kbd_config, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, t_xkb_kbd_config, name)
    __repr__ = _swig_repr
    __swig_setmethods__["model"] = _xkb_config.t_xkb_kbd_config_model_set
    __swig_getmethods__["model"] = _xkb_config.t_xkb_kbd_config_model_get
    if _newclass:model = _swig_property(_xkb_config.t_xkb_kbd_config_model_get, _xkb_config.t_xkb_kbd_config_model_set)
    __swig_setmethods__["layouts"] = _xkb_config.t_xkb_kbd_config_layouts_set
    __swig_getmethods__["layouts"] = _xkb_config.t_xkb_kbd_config_layouts_get
    if _newclass:layouts = _swig_property(_xkb_config.t_xkb_kbd_config_layouts_get, _xkb_config.t_xkb_kbd_config_layouts_set)
    __swig_setmethods__["variants"] = _xkb_config.t_xkb_kbd_config_variants_set
    __swig_getmethods__["variants"] = _xkb_config.t_xkb_kbd_config_variants_get
    if _newclass:variants = _swig_property(_xkb_config.t_xkb_kbd_config_variants_get, _xkb_config.t_xkb_kbd_config_variants_set)
    __swig_setmethods__["options"] = _xkb_config.t_xkb_kbd_config_options_set
    __swig_getmethods__["options"] = _xkb_config.t_xkb_kbd_config_options_get
    if _newclass:options = _swig_property(_xkb_config.t_xkb_kbd_config_options_get, _xkb_config.t_xkb_kbd_config_options_set)
    __swig_setmethods__["toggle_option"] = _xkb_config.t_xkb_kbd_config_toggle_option_set
    __swig_getmethods__["toggle_option"] = _xkb_config.t_xkb_kbd_config_toggle_option_get
    if _newclass:toggle_option = _swig_property(_xkb_config.t_xkb_kbd_config_toggle_option_get, _xkb_config.t_xkb_kbd_config_toggle_option_set)
    def __init__(self): 
        this = _xkb_config.new_t_xkb_kbd_config()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _xkb_config.delete_t_xkb_kbd_config
    __del__ = lambda self : None;
t_xkb_kbd_config_swigregister = _xkb_config.t_xkb_kbd_config_swigregister
t_xkb_kbd_config_swigregister(t_xkb_kbd_config)

class t_xkb_settings(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, t_xkb_settings, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, t_xkb_settings, name)
    __repr__ = _swig_repr
    __swig_setmethods__["mainw"] = _xkb_config.t_xkb_settings_mainw_set
    __swig_getmethods__["mainw"] = _xkb_config.t_xkb_settings_mainw_get
    if _newclass:mainw = _swig_property(_xkb_config.t_xkb_settings_mainw_get, _xkb_config.t_xkb_settings_mainw_set)
    __swig_setmethods__["tray_icon"] = _xkb_config.t_xkb_settings_tray_icon_set
    __swig_getmethods__["tray_icon"] = _xkb_config.t_xkb_settings_tray_icon_get
    if _newclass:tray_icon = _swig_property(_xkb_config.t_xkb_settings_tray_icon_get, _xkb_config.t_xkb_settings_tray_icon_set)
    __swig_setmethods__["current"] = _xkb_config.t_xkb_settings_current_set
    __swig_getmethods__["current"] = _xkb_config.t_xkb_settings_current_get
    if _newclass:current = _swig_property(_xkb_config.t_xkb_settings_current_get, _xkb_config.t_xkb_settings_current_set)
    __swig_setmethods__["group_policy"] = _xkb_config.t_xkb_settings_group_policy_set
    __swig_getmethods__["group_policy"] = _xkb_config.t_xkb_settings_group_policy_get
    if _newclass:group_policy = _swig_property(_xkb_config.t_xkb_settings_group_policy_get, _xkb_config.t_xkb_settings_group_policy_set)
    __swig_setmethods__["default_group"] = _xkb_config.t_xkb_settings_default_group_set
    __swig_getmethods__["default_group"] = _xkb_config.t_xkb_settings_default_group_get
    if _newclass:default_group = _swig_property(_xkb_config.t_xkb_settings_default_group_get, _xkb_config.t_xkb_settings_default_group_set)
    __swig_setmethods__["never_modify_config"] = _xkb_config.t_xkb_settings_never_modify_config_set
    __swig_getmethods__["never_modify_config"] = _xkb_config.t_xkb_settings_never_modify_config_get
    if _newclass:never_modify_config = _swig_property(_xkb_config.t_xkb_settings_never_modify_config_get, _xkb_config.t_xkb_settings_never_modify_config_set)
    __swig_setmethods__["config_changed"] = _xkb_config.t_xkb_settings_config_changed_set
    __swig_getmethods__["config_changed"] = _xkb_config.t_xkb_settings_config_changed_get
    if _newclass:config_changed = _swig_property(_xkb_config.t_xkb_settings_config_changed_get, _xkb_config.t_xkb_settings_config_changed_set)
    __swig_setmethods__["kbd_config"] = _xkb_config.t_xkb_settings_kbd_config_set
    __swig_getmethods__["kbd_config"] = _xkb_config.t_xkb_settings_kbd_config_get
    if _newclass:kbd_config = _swig_property(_xkb_config.t_xkb_settings_kbd_config_get, _xkb_config.t_xkb_settings_kbd_config_set)
    __swig_setmethods__["next"] = _xkb_config.t_xkb_settings_next_set
    __swig_getmethods__["next"] = _xkb_config.t_xkb_settings_next_get
    if _newclass:next = _swig_property(_xkb_config.t_xkb_settings_next_get, _xkb_config.t_xkb_settings_next_set)
    def __init__(self): 
        this = _xkb_config.new_t_xkb_settings()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _xkb_config.delete_t_xkb_settings
    __del__ = lambda self : None;
t_xkb_settings_swigregister = _xkb_config.t_xkb_settings_swigregister
t_xkb_settings_swigregister(t_xkb_settings)

class t_xkb_config(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, t_xkb_config, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, t_xkb_config, name)
    __repr__ = _swig_repr
    __swig_setmethods__["engine"] = _xkb_config.t_xkb_config_engine_set
    __swig_getmethods__["engine"] = _xkb_config.t_xkb_config_engine_get
    if _newclass:engine = _swig_property(_xkb_config.t_xkb_config_engine_get, _xkb_config.t_xkb_config_engine_set)
    __swig_setmethods__["group_names"] = _xkb_config.t_xkb_config_group_names_set
    __swig_getmethods__["group_names"] = _xkb_config.t_xkb_config_group_names_get
    if _newclass:group_names = _swig_property(_xkb_config.t_xkb_config_group_names_get, _xkb_config.t_xkb_config_group_names_set)
    __swig_setmethods__["variants"] = _xkb_config.t_xkb_config_variants_set
    __swig_getmethods__["variants"] = _xkb_config.t_xkb_config_variants_get
    if _newclass:variants = _swig_property(_xkb_config.t_xkb_config_variants_get, _xkb_config.t_xkb_config_variants_set)
    __swig_setmethods__["settings"] = _xkb_config.t_xkb_config_settings_set
    __swig_getmethods__["settings"] = _xkb_config.t_xkb_config_settings_get
    if _newclass:settings = _swig_property(_xkb_config.t_xkb_config_settings_get, _xkb_config.t_xkb_config_settings_set)
    __swig_setmethods__["variant_index_by_group"] = _xkb_config.t_xkb_config_variant_index_by_group_set
    __swig_getmethods__["variant_index_by_group"] = _xkb_config.t_xkb_config_variant_index_by_group_get
    if _newclass:variant_index_by_group = _swig_property(_xkb_config.t_xkb_config_variant_index_by_group_get, _xkb_config.t_xkb_config_variant_index_by_group_set)
    __swig_setmethods__["application_map"] = _xkb_config.t_xkb_config_application_map_set
    __swig_getmethods__["application_map"] = _xkb_config.t_xkb_config_application_map_get
    if _newclass:application_map = _swig_property(_xkb_config.t_xkb_config_application_map_get, _xkb_config.t_xkb_config_application_map_set)
    __swig_setmethods__["window_map"] = _xkb_config.t_xkb_config_window_map_set
    __swig_getmethods__["window_map"] = _xkb_config.t_xkb_config_window_map_get
    if _newclass:window_map = _swig_property(_xkb_config.t_xkb_config_window_map_get, _xkb_config.t_xkb_config_window_map_set)
    __swig_setmethods__["current_window_id"] = _xkb_config.t_xkb_config_current_window_id_set
    __swig_getmethods__["current_window_id"] = _xkb_config.t_xkb_config_current_window_id_get
    if _newclass:current_window_id = _swig_property(_xkb_config.t_xkb_config_current_window_id_get, _xkb_config.t_xkb_config_current_window_id_set)
    __swig_setmethods__["current_application_id"] = _xkb_config.t_xkb_config_current_application_id_set
    __swig_getmethods__["current_application_id"] = _xkb_config.t_xkb_config_current_application_id_get
    if _newclass:current_application_id = _swig_property(_xkb_config.t_xkb_config_current_application_id_get, _xkb_config.t_xkb_config_current_application_id_set)
    __swig_setmethods__["group_count"] = _xkb_config.t_xkb_config_group_count_set
    __swig_getmethods__["group_count"] = _xkb_config.t_xkb_config_group_count_get
    if _newclass:group_count = _swig_property(_xkb_config.t_xkb_config_group_count_get, _xkb_config.t_xkb_config_group_count_set)
    __swig_setmethods__["callback"] = _xkb_config.t_xkb_config_callback_set
    __swig_getmethods__["callback"] = _xkb_config.t_xkb_config_callback_get
    if _newclass:callback = _swig_property(_xkb_config.t_xkb_config_callback_get, _xkb_config.t_xkb_config_callback_set)
    __swig_setmethods__["callback_data"] = _xkb_config.t_xkb_config_callback_data_set
    __swig_getmethods__["callback_data"] = _xkb_config.t_xkb_config_callback_data_get
    if _newclass:callback_data = _swig_property(_xkb_config.t_xkb_config_callback_data_get, _xkb_config.t_xkb_config_callback_data_set)
    __swig_setmethods__["config_rec"] = _xkb_config.t_xkb_config_config_rec_set
    __swig_getmethods__["config_rec"] = _xkb_config.t_xkb_config_config_rec_get
    if _newclass:config_rec = _swig_property(_xkb_config.t_xkb_config_config_rec_get, _xkb_config.t_xkb_config_config_rec_set)
    def __init__(self): 
        this = _xkb_config.new_t_xkb_config()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _xkb_config.delete_t_xkb_config
    __del__ = lambda self : None;
t_xkb_config_swigregister = _xkb_config.t_xkb_config_swigregister
t_xkb_config_swigregister(t_xkb_config)


def xkb_config_initialize(*args):
  return _xkb_config.xkb_config_initialize(*args)
xkb_config_initialize = _xkb_config.xkb_config_initialize

def xkb_config_finalize():
  return _xkb_config.xkb_config_finalize()
xkb_config_finalize = _xkb_config.xkb_config_finalize

def xkb_config_update_settings(*args):
  return _xkb_config.xkb_config_update_settings(*args)
xkb_config_update_settings = _xkb_config.xkb_config_update_settings

def xkb_config_get_group_count():
  return _xkb_config.xkb_config_get_group_count()
xkb_config_get_group_count = _xkb_config.xkb_config_get_group_count

def xkb_config_get_group_map(*args):
  return _xkb_config.xkb_config_get_group_map(*args)
xkb_config_get_group_map = _xkb_config.xkb_config_get_group_map

def xkb_config_get_variant_map(*args):
  return _xkb_config.xkb_config_get_variant_map(*args)
xkb_config_get_variant_map = _xkb_config.xkb_config_get_variant_map

def xkb_config_set_group(*args):
  return _xkb_config.xkb_config_set_group(*args)
xkb_config_set_group = _xkb_config.xkb_config_set_group

def xkb_config_next_group():
  return _xkb_config.xkb_config_next_group()
xkb_config_next_group = _xkb_config.xkb_config_next_group

def xkb_config_variant_index_for_group(*args):
  return _xkb_config.xkb_config_variant_index_for_group(*args)
xkb_config_variant_index_for_group = _xkb_config.xkb_config_variant_index_for_group

def xkb_config_get_layout_desc(*args):
  return _xkb_config.xkb_config_get_layout_desc(*args)
xkb_config_get_layout_desc = _xkb_config.xkb_config_get_layout_desc

def xkb_config_add_layout(*args):
  return _xkb_config.xkb_config_add_layout(*args)
xkb_config_add_layout = _xkb_config.xkb_config_add_layout

def xkb_config_remove_group(*args):
  return _xkb_config.xkb_config_remove_group(*args)
xkb_config_remove_group = _xkb_config.xkb_config_remove_group

def xkb_config_window_changed(*args):
  return _xkb_config.xkb_config_window_changed(*args)
xkb_config_window_changed = _xkb_config.xkb_config_window_changed

def xkb_config_application_closed(*args):
  return _xkb_config.xkb_config_application_closed(*args)
xkb_config_application_closed = _xkb_config.xkb_config_application_closed

def xkb_config_window_closed(*args):
  return _xkb_config.xkb_config_window_closed(*args)
xkb_config_window_closed = _xkb_config.xkb_config_window_closed

def xkb_config_get_xkl_registry():
  return _xkb_config.xkb_config_get_xkl_registry()
xkb_config_get_xkl_registry = _xkb_config.xkb_config_get_xkl_registry

def xkb_config_get_max_layout_number():
  return _xkb_config.xkb_config_get_max_layout_number()
xkb_config_get_max_layout_number = _xkb_config.xkb_config_get_max_layout_number


